[[redirects]]
  from = 'https://www.linkedin.com/in/ravine-derick'
  to = 'https://www.linkedin.com/in/ravine-derick'
  status = 200
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}


